{
 "title": "Kepler Exporter Dashboard",
 "description": "Dashboard for Kepler Exporter",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(pod_curr_energy_in_pkg_millijoule, pod_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(pod_curr_energy_in_pkg_millijoule{pod_namespace=\"$namespace\"}, pod_name)"
    }
   },
   { "name": "coal", "query": "2.23" },
   { "name": "natural_gas", "query": "0.91" },
   { "name": "petroleum", "query": "2.13" }
  ]
 },
 "panels": [
  { "title": "Carbon Emissions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Namespace Carbon Footprint (pounds per kWh in 24hrs)",
   "type": "gauge",
   "description": "Using CO2 emissions  by power generation type as reported by US Energy Information Administration https://www.eia.gov/tools/faqs/faq.php?id=74&t=11",
   "gridPos": { "h": 11, "w": 21, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pod_curr_energy_in_pkg_millijoule{pod_namespace='$namespace'}[24h])/3600000000*$coal)",
     "legendFormat": "CO2 Coal"
    },
    {
     "expr": "sum(rate(pod_curr_energy_in_pkg_millijoule{pod_namespace='$namespace'}[24h])/3600000000*$petroleum)",
     "legendFormat": "CO2 Petroleum"
    },
    {
     "expr": "sum(rate(pod_curr_energy_in_pkg_millijoule{pod_namespace='$namespace'}[24h])/3600000000*$natural_gas)",
     "legendFormat": "CO2 Natural Gas"
    }
   ]
  },
  { "title": "Energy Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Pod Current Energy Consumption (mW*s)",
   "type": "timeseries",
   "description": "The mW per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(pod_curr_energy_in_pkg_millijoule{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[1m])/3",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(pod_curr_energy_in_core_millijoule{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[1m])/3",
     "legendFormat": "CPU"
    },
    {
     "expr": "rate(pod_curr_energy_in_dram_millijoule{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[1m])/3",
     "legendFormat": "DRAM"
    },
    {
     "expr": "rate(pod_curr_energy_in_gpu_millijoule{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[1m])/3",
     "legendFormat": "GPU"
    },
    {
     "expr": "rate(pod_curr_energy_in_other_millijoule{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[1m])/3",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Total Pod Energy Consumption (kW*h)",
   "type": "timeseries",
   "description": "Total W*s Consumed",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum_over_time(pod_curr_energy_in_pkg_millijoule{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[24h])*15/3/3600000000",
     "legendFormat": "Total"
    },
    {
     "expr": "sum_over_time(pod_curr_energy_in_core_millijoule{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[24h])*15/3/3600000000",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum_over_time(pod_curr_energy_in_dram_millijoule{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[24h])*15/3/3600000000",
     "legendFormat": "DRAM"
    },
    {
     "expr": "sum_over_time(pod_curr_energy_in_gpu_millijoule{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[24h])*15/3/3600000000",
     "legendFormat": "GPU"
    },
    {
     "expr": "sum_over_time(pod_curr_energy_in_other_millijoule{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[24h])*15/3/3600000000",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Total Pod Energy Consumption (kW*h) in $namespace in 24 hours",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(pod_curr_energy_in_pkg_millijoule{pod_namespace=\"$namespace\"}[24h])*15/3/3600000000",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Total Energy Consumption (kW*h) by Namespace in 24 hours",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum by (pod_namespace) (sum_over_time(pod_curr_energy_in_pkg_millijoule[24h])*15/3/3600000000)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}